import { Graph } from "types/graph";

export const pullRequestsGraphs: Record<number, Graph> = {
    2504556434: {
        "nodes": [
            { "id": "Champtercier", "group": 1 },
            { "id": "Cravatte", "group": 1 },
            { "id": "Count", "group": 1 },
            { "id": "OldMan", "group": 1 },
            { "id": "Valjean", "group": 2 },
            { "id": "Marguerite", "group": 3 },
            { "id": "Mme.deR", "group": 2 },
            { "id": "Isabeau", "group": 2 },
            { "id": "Gervais", "group": 2 },
            { "id": "Tholomyes", "group": 3 },
            { "id": "Listolier", "group": 3 },
            { "id": "Fameuil", "group": 3 },
            { "id": "Blacheville", "group": 3 },
            { "id": "Favourite", "group": 3 },
        ],
        "links": [
            { "source": "Marguerite", "target": "Valjean", "value": 1 },
            { "source": "Mme.deR", "target": "Valjean", "value": 1 },
            { "source": "Isabeau", "target": "Valjean", "value": 1 },
            { "source": "Gervais", "target": "Valjean", "value": 1 },
            { "source": "Count", "target": "Marguerite", "value": 15 },
            { "source": "Count", "target": "OldMan", "value": 15 },
            { "source": "Listolier", "target": "Tholomyes", "value": 4 },
            { "source": "Fameuil", "target": "Listolier", "value": 4 },
            { "source": "Listolier", "target": "OldMan", "value": 10 },
        ],
    },
    2012215313: {
        "nodes": [
            { "id": "Myriel", "group": 1 },
            { "id": "Napoleon", "group": 1 },
            { "id": "Mlle.Baptistine", "group": 1 },
            { "id": "Mme.Magloire", "group": 1 },
            { "id": "CountessdeLo", "group": 1 },
            { "id": "Geborand", "group": 1 },
            { "id": "Champtercier", "group": 1 },
            { "id": "Cravatte", "group": 1 },
            { "id": "Count", "group": 1 },
            { "id": "OldMan", "group": 1 },
            { "id": "Labarre", "group": 2 },
            { "id": "Valjean", "group": 2 },
            { "id": "Marguerite", "group": 3 },
            { "id": "Mme.deR", "group": 2 },
            { "id": "Isabeau", "group": 2 },
            { "id": "Gervais", "group": 2 },
            { "id": "Tholomyes", "group": 3 },
            { "id": "Listolier", "group": 3 },
            { "id": "Fameuil", "group": 3 },
            { "id": "Blacheville", "group": 3 },
            { "id": "Favourite", "group": 3 },
        ],
        "links": [
            { "source": "Napoleon", "target": "Myriel", "value": 1 },
            { "source": "Mlle.Baptistine", "target": "Myriel", "value": 8 },
            { "source": "Mme.Magloire", "target": "Myriel", "value": 10 },
            { "source": "Mme.Magloire", "target": "Mlle.Baptistine", "value": 6 },
            { "source": "CountessdeLo", "target": "Myriel", "value": 1 },
            { "source": "Geborand", "target": "Myriel", "value": 1 },
            { "source": "Champtercier", "target": "Myriel", "value": 1 },
            { "source": "Cravatte", "target": "Myriel", "value": 1 },
            { "source": "Count", "target": "Myriel", "value": 2 },
            { "source": "OldMan", "target": "Myriel", "value": 1 },
            { "source": "Valjean", "target": "Labarre", "value": 1 },
            { "source": "Valjean", "target": "Mme.Magloire", "value": 3 },
            { "source": "Valjean", "target": "Mlle.Baptistine", "value": 3 },
            { "source": "Valjean", "target": "Myriel", "value": 5 },
            { "source": "Marguerite", "target": "Valjean", "value": 1 },
            { "source": "Mme.deR", "target": "Valjean", "value": 1 },
            { "source": "Isabeau", "target": "Valjean", "value": 1 },
            { "source": "Gervais", "target": "Valjean", "value": 1 },
            { "source": "Listolier", "target": "Tholomyes", "value": 4 },
            { "source": "Fameuil", "target": "Tholomyes", "value": 4 },
            { "source": "Fameuil", "target": "Listolier", "value": 4 },
            { "source": "Listolier", "target": "OldMan", "value": 10 },
        ],
    }
}
