@startuml
autonumber
' Search
participant Пользователь as U

loop пользователь набирает запрос / выбирает параметры
    U --> ReposMediator: ReposMediator.searchTerm
    activate ReposMediator
    U --> ReposMediator: ReposMediator.sortBy
    ReposMediator --> SearchTS: SearchTS.run
    activate SearchTS
    ReposMediator <-- SearchTS: SearchTS.isFetching = true
    U <-- ReposMediator: ReposMediator.isFetching = true
end

SearchTS --> RepoMapper: RepoMapper.read
activate RepoMapper
RepoMapper --> DatabaseSearchRepo: read
activate DatabaseSearchRepo

alt успешно
    RepoMapper <-- DatabaseSearchRepo: RepoResponse[]
    SearchTS <-- RepoMapper: Repo[]
    ReposMediator <-- SearchTS: Repo[]
    ReposMediator <-- SearchTS: isFetching = false
    ReposMediator <-- SearchTS: isInitialized = true
    alt данные по запросу есть
        U <-- ReposMediator: RepoStore.items

        U --> ReposMediator : ReposMediator.requestSortBy
        U <-- ReposMediator : ReposMediator.items
    else данных нет
        U <-- ReposMediator: RepoStore.nothingFound
    end
else ошибка
    RepoMapper <-- DatabaseSearchRepo: Error
    deactivate DatabaseSearchRepo
    SearchTS <-- RepoMapper: Error
    deactivate RepoMapper
    ReposMediator <-- SearchTS: SearchTS.error
    ReposMediator <-- SearchTS: isFetching = false
    alt предвиденная ошибка
        ReposMediator <-- SearchTS: isInitialized = true
    else непредвиденная ошибка
        ReposMediator <-- SearchTS: isInitialized = false
    end

    deactivate SearchTS
    U <-- ReposMediator: ReposMediator.error
end

deactivate ReposMediator

@enduml
